openapi: 3.0.0
info:
  description: >
    This endpoint provides metadata about Genres.
    Known as a 'category' in our legacy API, a Program or a Channel as a whole may be associated with a number of Genres
  version: 1.0.0
  title: Genre metadata
tags:
  - name: Genres
    description: |
      Known as a 'category' in our legacy API, a Program or a Channel as a whole may be associated with a number of Genres
servers:
  - url: 'https://demo.aminocom.com/api/metadata/v1/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
  - bearerAuth: []         # use the same name as above
paths:

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /genres:
    get:
      tags:
      - Genres
      summary: Get an index of genres
      description: |
        * **Available since:** 2019-06 (BPLAT-4173)
      operationId: indexGenres
      parameters:
      - in: query
        name: language
        required: false
        description: >-
          The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).
          # TODO: If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.
          If this is omitted the system defined default will be used.
          If the requested language is not available then the system will return translations in order of the system defined preferences"
        schema:
          type: string
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - id
                      properties:
                        type:
                          type: string
                          example: Genre
                        id:
                          type: string
                          example: cc96d60f-8dc3-4a00-9d1f-761fe4933d8a
                          description: >-
                            The id of the genre entity
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/EnrichedMetadata/GenreEntity.yml#/GenreEntity"
        '400':
          description: Standard error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/ErrorEntity.yml#/Error"

