openapi: 3.0.0
info:
  description: >-
    Market segmentation allows us to flexibly group users together by shared characteristics in order to provide services
    that are more relevant to them.  See also the user management API for a PUT method.
  version: "1.0.0"
  title: "Market Segments"
tags:
- name: Market Segmentation
  description: >-
    Market segmentation allows us to flexibly group users together by shared characteristics in order to provide services
    that are more relevant to them.
servers:
- url: 'https://demo.aminocom.com/api/users/v4/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
- bearerAuth: []         # use the same name as above
paths:

# ------------------------------------------------------------------------

  /users/{user_id}/relationships/market_segments:
    get:
      tags:
      - Market Segmentation
      summary: >- 
        Get the market segments for a particular user
        See also the admin user configuration section for PUT.
      operationId: getUserMarketSegments
      parameters:
        - in: path
          name: user_id
          required: true
          description: The user identity (please do not use an email address to identify the user)
          schema:
            type: string
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          example: MarketSegment
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "bab838b3-def8-4bff-87ed-66e663134f50"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/v4/snippets/Config/MarketSegment.yml#/MarketSegment"