openapi: 3.0.0
info:
  description: >-
    Certain contents are not allowed to be viewed outside of home network.
    We need to provide functionality to restrict playback of those contents to defined IP range.
  version: "1.0.0"
  title: "Network permissions"
tags:
- name: Network permissions
servers:
- url: 'https://demo.aminocom.com/api/config/v1/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
- bearerAuth: []         # use the same name as above
paths:

# ------------------------------------------------------------------------------------------------------------------------------------

  /network_permissions:
    get:
      tags:
      - Network permissions
      summary: Get an index of Network permissions.
      operationId: indexNetworkPermissions

      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - id
                      properties:
                        type:
                          type: string
                          example: NetworkPermission
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "77273018-6fa1-4a0b-ac5f-64eee62c1d7d"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/Config/NetworkPermission.yml#/NetworkPermission"