openapi: 3.0.0
info:
  description: >-
    Certain contents are not allowed to be viewed outside of home network.
    We need to provide functionality to restrict playback of those contents to defined IP range.
  version: "1.0.0"
  title: "Network permissions"
tags:
- name: Network permissions
- name: Channel config
servers:
- url: 'https://demo.aminocom.com/api/config/v1/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
- bearerAuth: []         # use the same name as above
paths:

# ------------------------------------------------------------------------------------------------------------------------------------

  /channels/{channel_id}/relationships/network_permissions:
    post:
      tags:
      - Channel config
      summary: Link a channel to one or more network permissions
      operationId: createNetworkPermissionLink
      parameters:
        - in: path
          name: channel_id
          required: true
          description: The identity of the channel to create a relationship for
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - data
              properties:
                data:
                  type: array
                  items:
                    type: object
                    required:
                    - type
                    - id
                    properties:
                      type:
                        type: string
                        example: NetworkPermission
                      id:
                        type: string
                        description: "The id of the entity being referenced"
                        example: "77273018-6fa1-4a0b-ac5f-64eee62c1d7d"
      responses:
        '201':
          description: |
            Successful response.
          content:
            text/plain:
              schema:
                type: string
                example: CREATED
                description: |
                  Clients are advised NOT to use the body of the response to determine success or failure, but SHOULD rather
                  rely on the HTTP status code being 201 to indicate success.

# ------------------------------------------------------------------------------------------------------------------------------------

  /channels/{channel_id}/relationships/network_permissions/{network_permission_id}:
    delete:
      tags:
      - Channel config
      summary: Remove a NetworkPermission from a Channel
      operationId: deleteNetworkPermissionLink
      parameters:
        - in: path
          name: channel_id
          required: true
          description: The identity of the channel to create a relationship for
          schema:
            type: string
        - in: path
          name: network_permission_id
          required: true
          description: The identity of the NetworkPermission to remove from the channel
          schema:
            type: string
      responses:
        '204':
          description: |
            The resource was deleted successfully.  No response body will be sent.


# ------------------------------------------------------------------------------------------------------------------------------------

  /network_permissions:
    get:
      tags:
      - Network permissions
      summary: Get an index of Network permissions.
      operationId: indexNetworkPermissions

      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - id
                      properties:
                        type:
                          type: string
                          example: NetworkPermission
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "77273018-6fa1-4a0b-ac5f-64eee62c1d7d"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/Config/NetworkPermission.yml#/NetworkPermission"

    post:
      tags:
      - Network permissions
      summary: Create a new Network permission.
      operationId: createNetworkPermission
      requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/Config/NetworkPermission.yml#/NetworkPermission"
      responses:
        '201':
          description: |
            Successful response.
          content:
            text/plain:
              schema:
                type: string
                example: CREATED
                description: |
                  Clients are advised NOT to use the body of the response to determine success or failure, but SHOULD rather
                  rely on the HTTP status code being 201 to indicate success.

# ------------------------------------------------------------------------------------------------------------------------------------

  /network_permissions/{network_permission_id}:
    delete:
      tags:
      - Network permissions
      summary: Delete a Network permission
      operationId: deleteNetworkPermissions
      parameters:
        - in: path
          name: network_permission_id
          required: true
          description: The identity of the network permission to delete
          schema:
            type: string
      responses:
        204:
          description: |
            The resource was deleted successfully, no response body is needed


    put:
      tags:
      - Network permissions
      summary: Update a Network permission
      operationId: updateNetworkPermissions
      parameters:
        - in: path
          name: network_permission_id
          required: true
          description: The identity of the network permission to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/Config/NetworkPermission.yml#/NetworkPermission"
      responses:
        204:
          description: |
            The resource was updated successfully, no response body is needed