openapi: 3.0.0
info:
  description: >-
    A user is a physical person consuming the services offered by Move.
    In the future we may introduce the concept of an Account where One Account Has Many User, but currently there is no distinction between User and Account
    Users may be subscribers or guests.
  version: "1.0.0"
  title: "Users"
tags:
- name: Users
  description: >-
    A user is a physical person consuming the services offered by Move.
- name: Market Segmentation
  description: >-
    Market segmentation allows us to flexibly group users together by shared characteristics in order to provide services
    that are more relevant to them.
servers:
- url: 'https://demo.aminocom.com/api/users/v1/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
- bearerAuth: []         # use the same name as above
paths:

# ------------------------------------------------------------------------------------------------------------------------------------

  /users:
    get:
      tags:
      - Users
      summary: Get an index of Users.
      operationId: indexUsers
      parameters:
        - in: query
          name: page_number
          required: false
          description: "The page number (100 results per page) of results to retrieve.  If this parameter is ommitted then it is assumed to be 1 (not zero based, 1 means the first page)"
          schema:
            type: integer
        - in: query
          name: registration_status
          required: false
          description: "An optional parameter to filter by a particular registration state.  By default all users will be returned."
          schema:
            type: string

      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - id
                      properties:
                        type:
                          type: string
                          example: User
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "e07a7130-4048-4a5f-bfa4-7adc5a5e860e"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/Config/UserEntity.yml#/UserEntity"

    post:
      tags:
      - Users
      summary: Create a user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/Config/UserEntity.yml#/UserEntity"
      responses:
        '201':
          description: |
            Successful response.
          headers:
            Set-Cookie:
              schema:
                type: string
              description: "Session cookie"
          content:
            text/plain:
              schema:
                type: string
                example: CREATED
                description: |
                  Clients are advised NOT to use the body of the response to determine success or failure, but SHOULD rather
                  rely on the HTTP status code being 201 to indicate success.

# ------------------------------------------------------------------------

  /users/{user_id}/relationships/market_segments:
   
    put:
      tags:
      - Market Segmentation
      summary: >-
        Amend what segments a user belongs to.  This will replace all the relationships (it is NOT additive).
        See also the user configuration section for GET.
      operationId: createUserMarketSegments
      parameters:
        - in: path
          name: user_id
          required: true
          description: The user identity (please do not use an email address to identify the user)
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    description: "The id of the entity being referenced"
                    example: "bab838b3-def8-4bff-87ed-66e663134f50"
                  type:
                    type: string
                    example: MarketSegment

      responses:
        '204':
          description: |
            Successful response.          