openapi: 3.0.0
info:
  description: >
    This endpoint provides metadata about Genres.
    Known as a 'category' in our legacy API, a Program or a Channel as a whole may be associated with a number of Genres
  version: 1.0.0
  title: Genre metadata
tags:
  - name: Genres
    description: |
      Known as a 'category' in our legacy API, a Program or a Channel as a whole may be associated with a number of Genres
servers:
  - url: 'https://demo.aminocom.com/api/metadata/v1/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
  - bearerAuth: []         # use the same name as above
paths:

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /genres/{genre_id}/programs:
    get:
      summary: "Get list of programs for a genre."
      tags:
      - Genres
      operationId: SeeGenrePrograms
      parameters:
      - in: "path"
        name: "genre_id"
        required: true
        description: "The identifier of the genre"
        schema:
          type: string
      - in: query
        name: language
        required: false
        description: >-
          The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).
          If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.
          If the requested language is not available then the system will return translations in order of the system defined preferences"
        schema:
          type: string
      - in: query
        name: sort
        required: false
        description: >-
          Please see http://jsonapi.org/format/#fetching-sorting
          The following are attributes to sort on: [program.title|program.release_year].
          Future versions may include sorting on [program.original_title]
          The default sort order is by program.release_year descending
        schema:
          type: string
      - in: query
        name: filter
        required: false
        description: >-
          Please see http://jsonapi.org/recommendations/#filtering
          The following are attributes to filter on: [content_rating.adult|program.release_year]
        schema:
          type: string

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - id
                      properties:
                        type:
                          type: string
                          example: Genre
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "cc96d60f-8dc3-4a00-9d1f-761fe4933d8a"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/v1/snippets/EnrichedMetadata/ProgramEntity.yml#ProgramEntity"
        '400':
          description: Standard error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/v1/snippets/General/ErrorEntity.yml#/Error"
