openapi: 3.0.0
info:
  description: >
    This endpoint provides metadata about Series.

    Multiple Programs are grouped into a Series which consists of several Episodes that belong to Seasons
    A Program can be either part of a Series (in which case it is an Episode) or stand alone.
    Note: The plural of a single Series is Series
  version: 1.0.0
  title: Series metadata
tags:
  - name: Series
    description: |
      Multiple Programs are grouped into a Series which consists of several Episodes that belong to Seasons
      A Program can be either part of a Series (in which case it is an Episode) or stand alone.
      Note: The plural of a single Series is Series
servers:
  - url: 'https://demo.aminocom.com/api/metadata/v1/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
  - bearerAuth: []         # use the same name as above
paths:

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /series:
    get:
      summary: "Get an index of series, sorted by release_year in descending order (get the newest releases first)"
      tags:
      - Series
      operationId: GetSeriesIndex
      parameters:
        - in: query
          name: language
          required: false
          description: >-
            The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).
            If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.
            If the requested language is not available then the system will return translations in order of the system defined preferences"
          schema:
            type: string
        - in: query
          name: page_number
          required: false
          description: >-
            The page number (100 results per page) of results to retrieve.  If this parameter is ommitted then it is assumed to be 1 (not zero based, 1 means the first page)
          schema:
            type: string
        - in: query
          name: sort
          required: false
          description: >-
            Please see http://jsonapi.org/format/#fetching-sorting
            The following are attributes to sort on: [series.title|series.release_year]
          schema:
            type: string
        - in: query
          name: filter
          required: false
          description: >-
            Please see http://jsonapi.org/recommendations/#filtering
            The following are attributes to filter on: [content_rating.adult|genre.name|series.release_year]
          schema:
            type: string
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                type: object
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - id
                      properties:
                        type:
                          type: string
                          example: Series
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "f9df1401-9d25-48e0-b5d6-0745a86bd975"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/v1/snippets/EnrichedMetadata/SeriesEntity.yml#SeriesEntity"

        '400':
          description: Standard error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/v1/snippets/General/ErrorEntity.yml#Error"

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /series/{series_id}:
    get:
      summary: "Get an individual series.  NOTE:  This endpoint will *always* include [Season|Genre|CreditedPerson] relationships and DOES NOT support the `included` parameter."
      tags:
      - "Series"
      operationId: "GetSeriesEntity"
      parameters:
        - in: path
          name: series_id
          required: true
          description: The identifier of the series
          schema:
            type: string
        - in: query
          name: language
          required: false
          description: >-
            The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).
            If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.
            If the requested language is not available then the system will return translations in order of the system defined preferences"
          schema:
            type: string

      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                type: object
                required:
                - data
                properties:
                  data:
                    type: object
                    required:
                    - type
                    - id
                    properties:
                      type:
                        type: string
                        example: Series
                      id:
                        type: string
                        description: "The id of the entity being referenced"
                        example: "f9df1401-9d25-48e0-b5d6-0745a86bd975"
                      attributes:
                        $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/v1/snippets/EnrichedMetadata/SeriesEntity.yml#SeriesEntity"
                  included:
                    type: array
                    description: "This key MUST NOT be included if the `included` parameter is not used in the request URL"
                    items:
                      type: object
                      description: "Note that different sorts of entity may be included (this array is not guaranteed to be homogenous), but the Swagger definition does not allow including more than one example of an item of an array so only one type is shown."
                      properties:
                        type:
                          type: string
                          example: Season
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "e00adc12-6fcb-4176-832f-45a0b84aa908"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/v1/snippets/EnrichedMetadata/SeasonEntity.yml#SeasonEntity"
        '400':
          description: Standard error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/v1/snippets/General/ErrorEntity.yml#Error"

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /series/{series_id}/programs:
    get:
      summary: >-
        Get list of programs for a series - this should only be Programs that are *directly* related to a Series and NOT Programs that are transitively related through an Episode.
      tags:
      - Series
      operationId: SeeSeriesPrograms
      parameters:
        - in: "path"
          name: "series_id"
          required: true
          description: "The identifier of the series"
          schema:
            type: string
        - in: query
          name: language
          required: false
          description: >-
            The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).
            If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.
            If the requested language is not available then the system will return translations in order of the system defined preferences"
          schema:
            type: string
        - in: query
          name: sort
          required: false
          description: >-
            Please see http://jsonapi.org/format/#fetching-sorting
            The following are attributes to sort on: [program.title|program.release_year]
          schema:
            type: string
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                type: object
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - id
                      properties:
                        type:
                          type: string
                          example: Program
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "cc96d60f-8dc3-4a00-9d1f-761fe4933d8a"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/v1/snippets/EnrichedMetadata/ProgramEntity.yml#ProgramEntity"
        '400':
          description: Standard error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/v1/snippets/General/ErrorEntity.yml#Error"
