openapi: 3.0.0
info:
  description: >-
    A BroadcastSlot is a time period on a Channel in which a Program may be shown.
    Our BroadcastSlot entity is just a single appearance of a Program on a Channel.
    We store information about the time slot as well as a title for the slot.
    Note: The title of a BroadcastSlot does not have to be the same as the title of the Program in that slot.
    In English a schedule is understood to be a list or a plan and so we avoid using that word for a single item.
  version: 1.0.0
  title: BroadcastSlot metadata
tags:
- name: BroadcastSlots
  description: >-
    A BroadcastSlot is a time period on a Channel in which a Program may be shown.
    Our BroadcastSlot entity is just a single appearance of a Program on a Channel.
    We store information about the time slot as well as a title for the slot.
    Note: The title of a BroadcastSlot does not have to be the same as the title of the Program in that slot.
    In English a schedule is understood to be a list or a plan and so we avoid using that word for a single item.
servers:
- url: 'https://demo.aminocom.com/api/metadata/v1/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
- bearerAuth: []         # use the same name as above
paths:

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


  /broadcast_slots/{channel_id}/{yyyy-mm-dd}:
    get:
      summary: Get an index of BroadcastSlots
      description:  |
        * **Available since:** 2020-03 (BPLAT-10388)
        * We do not support including related resources in the index view.
      tags:
      - BroadcastSlots
      operationId: GetBroadcastSlotsIndex
      parameters:
        - in: path
          name: channel_id
          required: true
          description: The ID of the channel to fetch EPG for.
          schema:
            type: string
        - in: path
          name: yyyy-mm-dd
          required: true
          example: 2020-02-21
          description: >-
            Date for which to get EPG for. The API returns EPG within a window starting from 04:00 AM on the given date until 04:00 AM on the following date.
          schema:
            type: string
        - in: query
          name: language
          required: false
          description: >-
            The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).
            If this is omitted the system defined default will be used.
            If the requested language is not available then the system will return translations in order of the system defined preferences
          schema:
            type: string
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                required:
                - data
                - included
                properties:
                  data:
                    type: array
                    items:
                      $ref: "../../snippets/Schedule/BroadcastSlotEntity.yml#/BroadcastSlotEntity"
                  included:
                    type: array
                    items:
                      $ref: "../../snippets/Channel/ChannelEntity.yml#/ChannelEntity"

        400:
          description: Standard error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/ErrorEntity.yml#/Error"

