openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Channel (Legacy)"
  description: >-
    A Channel is a source of content in the form of stream or signal, which can be watched / listened on a multimedia device.
    A Channel is distinct from VOD in that a Channel is a live stream.
    A Channel may be either Premium (requiring a Subscription) or free (otherwise).
tags:
- name: Channel
servers:
- url: 'https://boox.fi/api'
paths:

  /v3.1/channels:
    get:
      summary: Return a publicly cacheable list of channels that are not user specific
      description: >-
        This endpoint can be publicly cached as it does not have any user specific information.  The device
        is encouraged to respect the cache-control headers in order to comply with our API development guidelines.
      tags:
      - Channel
      operationId: indexGeneralChannels
      parameters:
      - in: query
        name: service
        description: The service to which the user belongs
        required: true
        schema:
          type: string
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/legacy/snippets/channel/Channel31General.yml#/Channel31General"