openapi: 3.0.0
info:
  version: "2.0.0"
  title: "Profile recording"
tags:
- name: Recordings
  description: >-
    A recording represents a broadcast slot that the user wants to have recorded.
    A Recording may or may not be available for viewing, depending of whether the broadcast slot has been successfully recorded.
- name: Automated Recording Requests
  description: >-
    An Automated Recording Request represents a request by a user to automatically record specific broadcast slots for them as they become available.
- name: Recording Groups
  description: >-
    Recording Groups are groups of Recordings available for viewing, typically a Series.
servers:
- url: 'https://demo.aminocom.com/api/recordings/v2/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
- bearerAuth: []         # use the same name as above
paths:

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# RECORDINGS
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /user_profiles/{user_profile_id}/recordings:
    post:
      description: |
        * **Available since:** NOT YET AVAILABLE
      summary: # TODO
      tags:
        - Recordings
      operationId: createRecordedSlot
      # TODO

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /user_profiles/{user_profile_id}/recordings/{recording_id}:
    patch:
      description: |
        * **Available since:** NOT YET AVAILABLE
      tags:
      - Recordings
      summary: # TODO
      operationId: updateRecordedSlot
      # TODO

    delete:
      tags:
      - Recordings
      summary: # TODO
      description: |
        * **Available since:** NOT YET AVAILABLE
      operationId: deleteRecordedSlot
      # TODO

  /user_profiles/{user_profile_id}/recordings/bulk_delete_recordings:
    post:
      description: |
        * **Available since:** NOT YET AVAILABLE
      tags:
        - Recordings
      summary: # TODO
      operationId: updateRecordedSlot
      # TODO

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# AUTOMATED RECORDING REQUESTS
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /user_profiles/{user_profile_id}/auto_recording_requests:
    get:
      description: |
        * **Available since:** NOT YET AVAILABLE
      summary: # TODO
      tags:
        - Automated Recording Requests
      operationId: indexRecordingRequests
      # TODO

    post:
      description: |
        * **Available since:** NOT YET AVAILABLE
      summary: # TODO
      tags:
        - Automated Recording Requests
      operationId: createRecordingRequests
      # TODO

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /user_profiles/{user_profile_id}/auto_recording_requests/{recording_request_id}:
    patch:
      description: |
        * **Available since:** NOT YET AVAILABLE
      summary: # TODO
      tags:
        - Automated Recording Requests
      operationId: updateRecordingRequests
      # TODO

    delete:
      description: |
        * **Available since:** NOT YET AVAILABLE
      summary: # TODO
      tags:
        - Automated Recording Requests
      operationId: deleteRecordingRequests
      # TODO

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# RECORDING GROUPS
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /user_profiles/{user_profile_id}/recordings/recording_groups:
    get:
      description: |
        * **Available since:** 2019-10 (BPLAT-12048)
      summary: An index of all of the recording groups for a specific user profile
      tags:
        - Recording Groups
      operationId: indexRecordingGroups
      parameters:
        - in: path
          name: user_profile_id
          required: true
          description: The identity of the user profile to fetch recording groups for.
          schema:
            type: string
        - in: query
          name: page_number
          required: false
          description: Page number if the results have more items than ipp. Default = 1
          schema:
            type: integer
        - in: query
          name: language
          description: >-
            The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).
            If this is omitted the system defined default will be used. If the requested language is not available
            then the system will return translations in order of the system defined preferences
          required: false
          schema:
            type: string

      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - id
                      properties:
                        type:
                          type: array
                          example: RecordingGroup
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "84eb61a9-75d4-42c7-8c15-84c3d7776227"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/UserRecordings/RecordingGroupEntity.yml#/RecordingGroupEntity"

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /user_profiles/{user_profile_id}/recordings/recording_groups/{recording_group_id}/recordings:
    get:
      description: |
        * **Available since:** 2019-10 (BPLAT-10674)
      summary: An index of the recordings for a specific recording group
      tags:
        - Recording Groups
      operationId: getRecordingsForGroup
      parameters:
        - in: path
          name: user_profile_id
          required: true
          description: The identity of the user profile to fetch recording groups for.
          schema:
            type: string
        - in: path
          name: recording_group_id
          required: true
          description: The identity of the recording group to fetch recordings for.
          schema:
            type: string
        - in: query
          name: page_number
          required: false
          description: Page number if the results have more items than ipp. Default = 1
          schema:
            type: integer
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - id
                      properties:
                        type:
                          type: array
                          example: Recording
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "84eb61a9-75d4-42c7-8c15-84c3d7776227"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/UserRecordings/UserRecordingEntity.yml#/UserRecordingEntity"

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /user_profiles/{user_profile_id}/recordings/recording_groups/ungrouped/recordings:
    get:
      description: |
        * **Available since:** NOT YET AVAILABLE
      summary: # TODO
      tags:
        - Recording Groups
      operationId: indexUngroupedRecordingGroupRecordings
      # TODO
