ProductEntity:
  type: object
  properties:
    title:
      type: string
      example: Most Viewed
    description:
      type: string
      example: Most viewed products
    rank:
      type: integer
      example: 100
      description: A cue on how to rank this product in a display order
    images:
      type: array
      items:
        $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/v4/snippets/EnrichedMetadata/ImageValueObject.yml#ImageValueObject"
    type:
      type: string
      example: CATEGORY
    provider:
      type: string
      example: "cmore.fi"
    created_at_timestamp:
      type: integer
      example: 1513728000
      description: The Unix timestamp that the product was created at
    purchase_details:
      type: object
      properties:
        is_premium:
          type: boolean
          example: true
          description: If this is false then the product is free of charge
        price_currency_amount:
          type: float
          example: 12.23
          description: The float (double precision) amount of currency that was paid (some fiat currencies have three decimal points of precision)
        price_currency_iso4217:
          type: string
          example: EUR
          description: The ISO-4217 code of the currency (https://en.wikipedia.org/wiki/ISO_4217)
        last_chance:
          type: boolean
          example: true
          description: TO BE CONFIRMED
        highlight_as_new_product:
          type: boolean
          example: false
          description: This product is new and should be highlighted
    license_details:
      type: object
      properties:
        license_duration_seconds:
          type: integer
          example: 2592000
        recurring:
          type: boolean
          example: true
    availability:
      type: object
      properties:
        is_visible:
          type: boolean
          example: true
          description: If this is false then you should not display the product
        is_buyable:
          type: boolean
          example: true
          description: This indicates whether the product can currently be purchased or not
        visibility_start_timestamp:
          type: integer
          example: 1514764800
          description: The time after which this product should be displayed
        visibility_end_timestamp:
          type: integer
          example: 1546300800
          description: The time after which this product should no longer be displayed as available
    external_references:
      type: array
      items:
        type: object
        properties:
          external_reference_type:
            type: string
            example: "Hybris or iPhone or iPad"
          external_reference_id:
            type: string
            example: "1234567"
            description: "The foreign identity"
    tags:
      type: array
      items:
        type: string
        example: "home"