openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Logging in a user"
  description: >-
    These endpoints help you to authenticate a user
tags:
- name: User Authentication
servers:
- url: 'https://boox.fi'
paths:

  /auth/service:
    post:
      summary: Service login
      tags:
      - User Authentication
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
              - authParams
              properties:
                ver:
                  type: string
                  description: Version of the BooxTV application
                authParams:
                  type: string
                  description: Digest authentication
                  example: authParams=Digest+realm%3D%22service%22%2Cqop%3D%22auth%22%2Cnonce%3D%123456788912234566abcde%22%2Copaque%3D%123abcdefghi123abcdef1234abcde%22&uri=https%3A%2F%2Fcustomer.domain%2Fapi%2Fuser%2Fguest%2Flogin&requestMethod=GET&serviceUser=mobileclient
