openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Logging in a user"
  description: >-
    These endpoints help you to authenticate a user
tags:
- name: User Authentication
servers:
- url: 'https://boox.fi/api'
paths:

  /user/{user_email}/login:
    post:
      summary: This method logs a user in and returns a cookie containing a "usid" value
      description: >-
        The "usid" in the cookie can be used to authenticate users against legacy endpoints.
        REST endpoints require you to use a token supplied in the header.
      tags:
      - User Authentication
      operationId: loginUser
      parameters:
      - in: path
        name: user_email
        description: The email addressed used to identify the user
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
              - ver
              - device_id
              - platform
              - os_ver
              - service
              properties:
                ver:
                  type: string
                  description: Version of the BooxTV application
                device_id:
                  type: string
                  description: Unique identifier for the devices
                  example: boox10@booxtv.fi
                # Public keys are removed in code: booxmedia/src/interface/protected/modules/management/controllers/StbController.php:83
                chipset_id:
                  type: string
                  description: STB device chipset number/ID.  Please ask Amino how to calculate this.
                  example: BCM72604UB
                mac:
                  type: string
                  description: Ethernet interface MAC address