UserChannelLockingConfiguration:
  type: object
  required:
    - account_channel_lock_status
    - session_channel_lock_status
  properties:
    account_channel_lock_status:
      type: boolean
      description: >-
        Boolean flag to indicate whether the user wants to enable (true) or disable (false) channel locking on the account as a whole
        If this field is omitted then no change will be made to the account.
      example: true
      enum: [true,false]
    session_channel_lock_status:
      type: boolean
      description: >-
        Boolean flag to indicate whether the user wants to enable (true) or disable (false) channel locking for the session on the
        client that the call is made from.  This field will be omitted when the API responds to a GET request.
      example: true
      enum: [true,false]
    pin_code:
      type: integer
      description: >-
        The user client must supply the correct current PIN code in order for the change to take effect.
        This field will not be emitted from the API.
      example: 1234
    new_pin_code:
      type: integer
      description: >-
        This field should only be supplied in PUT requests when the user wants to change the PIN code.
        The PIN code must be numeric, otherwise a "400 Bad Request" response will be returned.
        This field will not be emitted from the API.
      example: 1234
    locked_channels:
      type: array
      description: An array of channels that are currently locked
      items:
        type: string
        example: 3bdb869c-4781-46f8-b00b-1a780664a7ab
        description: The id of a channel that is locked