UserChannelLockingConfiguration:
  type: object
  required:
    - locked_channels
  properties:
    session_channel_lock_status:
      type: boolean
      description: >-
        Boolean flag to indicate whether the user wants to enable (true) or disable (false) channel locking for the session on the
        client that the call is made from.  This field will be omitted when the API responds to a GET request.
      example: true
      enum: [true,false]
    locked_channels:
      type: array
      description: An array of channels that are currently locked.
      items:
        type: string
        example: 3bdb869c-4781-46f8-b00b-1a780664a7ab
        description: The id of a channel that is locked
    pin_code:
      type: integer
      description: >-
        This field will not ever be emitted from the API and should only be included in PATCH requests from the client.
        This field MUST be included in a PATCH request that sets the "new_pin_code"
        If this field does not match the stored PIN code when the user tries to PATCH the new_pin_code the API will respond with 403.
      example: 1234