swagger: "2.0"
info:
  description: |

  version: "1.0.0"
  title: "Subscription endpoints"
host: "demo.aminocom.com"
basePath: "/api/subscription/v1/"
tags:
- name: "Subscriptions"
  description: ""
schemes:
- "https"
paths:

  /user/{user_id}/products:
    get:
      summary: "Get an index of Products that a user is subscribed to"
      description: |
        * **Available since:** NOT YET AVAILABLE
      tags:
      - "Subscriptions"
      operationId: "GetSubscriptionsIndex"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: user_id
        type: string
        required: true
        description: "The identifier of the user (please do not use an email address, rather use a uuid or hash of their email address)"
      - in: query
        name: language
        type: string
        required: false
        description: >-
          The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).
          If this is omitted the system defined default will be used.
          If the requested language is not available then the system will return translations in order of the system defined preferences

      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            required:
            - data
            properties:
              data:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - id
                  properties:
                    type:
                      type: string
                      example: Channel
                    id:
                      type: string
                      description: "The id of the entity being referenced"
                      example: "89e3a147-2ff6-448f-959f-a6200434259d"
                    attributes:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/Subscription/ProductEntity.yml#/ProductEntity"
