openapi: 3.0.0
info:
  description: |

  version: "1.0.0"
  title: "Irdeto"
servers:
- url: 'https://demo.aminocom.com/api/irdeto/v1/'
tags:
- name: "Irdeto"
  description: ""
paths:

  /user/{user_id}/device/{device_id}/entitlements:
    post:
      summary: "Entitle device"
      description: "The device will call this Move API to request that Move call the Irdeto KMS and entitle the device"
      tags:
      - "Irdeto"
      operationId: "createDeviceEntitlement"
      parameters:
      - in: path
        name: user_id
        required: true
        description: "The user identifier (this should not be an email address)"
        schema:
          type: string
      - in: path
        name: device_id
        required: true
        description: "The serial number of the device "
        schema:
          type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                channel_id:
                  type: string
                  example: d64cc62d-cf26-4531-a605-c7fa873256ad
                  description: The Amino identifier of the channel.  The middleware will map this to the Irdeto identifier.

      responses:
        201:
          description: "Successful response"
          content:
            text/plain:
              schema:
                type: string
                example: OK

    delete:
      summary: "Remove entitlement from device"
      description: ""
      tags:
      - "Irdeto"
      operationId: "createDeviceEntitlement"
      parameters:
      - in: path
        name: user_id
        required: true
        description: "The user identifier (this should not be an email address)"
        schema:
          type: string
      - in: path
        name: device_id
        required: true
        description: "The serial number of the device"
        schema:
          type: string

      responses:
        200:
          description: "The device is no longer entitled"
          content:
            text/plain:
              schema:
                type: string
                example: OK
