ProductEntity:
  type: object
  required:
  properties:
    name:
      type: string
      example: "Yle sports bundle"
      description: The name under which the product is sold
    external_id:
      type: string
      example: "13"
      description: If this is sold externally (e.g. Hybris) then this is the external identity
