ProductEntity:
  type: object
  required:
  properties:
    id:
      type: string
      example: "cdf6b44c-2e44-41c7-9325-62d600431b5f"
      description: "The uuid of the product, used as our internal identifier"
    name:
      type: string
      example: "Yle sports bundle"
      description: The name under which the product is sold
    external_id:
      type: string
      example: "13"
      description: If this is sold externally (e.g. Hybris) then this is the external identity
