openapi: 3.0.0
info:
  description: |

  version: "1.0.0"
  title: "Irdeto"
servers:
- url: 'https://demo.aminocom.com/api/irdeto/v4/'
tags:
- name: "Irdeto"
  description: ""
paths:

  /user/{user_id}/device/{device_id}/entitlements:
    post:
      summary: "Entitle a set top box to watch DVB channels"
      description: >-
        The set top box will scan the frequency range and find the DVB triplets for the channels that it wants to entitle the user to.
        It will call this Move API to request that Move call the Irdeto KMS and entitle the device"
      tags:
      - "Irdeto"
      operationId: "createDeviceEntitlement"
      parameters:
      - in: path
        name: user_id
        required: true
        description: "The user identifier (this should not be an email address)"
        schema:
          type: string
      - in: path
        name: device_id
        required: true
        description: "The serial number of the device "
        schema:
          type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/v4/snippets/Irdeto/IrdetoEntitlementEntity.yaml#/IrdetoEntitlementEntity"

      responses:
        201:
          description: "Successful response"
          content:
            text/plain:
              schema:
                type: string
                example: OK

    delete:
      summary: "Remove entitlement from set top box"
      description: ""
      tags:
      - "Irdeto"
      operationId: "createDeviceEntitlement"
      parameters:
      - in: path
        name: user_id
        required: true
        description: "The user identifier (this should not be an email address)"
        schema:
          type: string
      - in: path
        name: device_id
        required: true
        description: "The serial number of the device"
        schema:
          type: string

      responses:
        200:
          description: "The device is no longer entitled"
          content:
            text/plain:
              schema:
                type: string
                example: OK
