openapi: 3.0.0
info:
  description: >-
    Users can optionally lock adult content from being displayed on their account.
  version: "1.0.0"
  title: "Channel locking"
tags:
- name: Channel locking
- name: PIN code management
servers:
- url: 'https://demo.aminocom.com/api/users/v1/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
- bearerAuth: []         # use the same name as above
paths:


# -------------------------------------------------------------------------------------------------------------------------------------

  /users/{user_id}/channel_lock:
    get:
      tags:
      - Channel locking
      summary: Set channel locking on or off
      operationId: setChannelLock
      parameters:
        - in: path
          name: user_id
          required: true
          description: The identity of the user to fetch lists for.  Please do not use an email address to identify the user.
          schema:
            type: string
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - id
                      properties:
                        type:
                          type: string
                          example: UserChannelLockingConfiguration
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "da00a320-2bae-49af-9687-298ed3f01361"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/Config/MarketSegment.yml#/MarketSegment"

    put:
      tags:
      - Channel locking
      summary: Set channel locking on or off
      operationId: setChannelLock
      parameters:
        - in: path
          name: user_id
          required: true
          description: The identity of the user to fetch lists for.  Please do not use an email address to identify the user.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/UserConfiguration/UserChannelLockingConfiguration.yml#/UserChannelLockingConfiguration"
      responses:
        204:
          description: |
            The resource was updated successfully, no response body is needed

        403:
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/ErrorEntity.yml#/Error"
                example:
                  id: 9303f876
                  code: f223db3
                  title: PIN code incorrect
                  details: >-
                    The PIN code that you supplied does not match the one we have stored for the account.



# -------------------------------------------------------------------------------------------------------------------------------------

  /users/{user_id}/pin_code:
    put:
      tags:
      - PIN code management
      summary: Change the PIN code for the user
      operationId: replacePINcode
      parameters:
        - in: path
          name: user_id
          required: true
          description: The identity of the user to fetch lists for.  Please do not use an email address to identify the user.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  required:
                    - new_pin_code
                    - current_pin_code
                  properties:
                    new_pin_code:
                      type: string
                      description: PIN code that conforms to the deployment requirements for a PIN code
                      example: 1234
                    current_pin_code:
                      type: string
                      description: The current PIN code.  If the user has not set their own code they should use the default PIN code.
      responses:
        204:
          description: |
            The resource was updated successfully, no response body is needed

        403:
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/ErrorEntity.yml#/Error"
                example:
                  id: da00a320
                  code: f223db3
                  title: PIN code incorrect
                  details: >-
                    The PIN code that you supplied does not match the one we have stored for the account.
