openapi: 3.0.0
info:
  description: >-
    Users can optionally lock adult content from being displayed on their account.
  version: "1.0.0"
  title: "Channel locking"
tags:
- name: Channel locking
servers:
- url: 'https://demo.aminocom.com/api/users/v1/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
- bearerAuth: []         # use the same name as above
paths:


# -------------------------------------------------------------------------------------------------------------------------------------

  /users/{user_id}/channel_lock_configuration:
    get:
      description: |
        * **Available since:** NOT YET AVAILABLE
      tags:
      - Channel locking
      summary: Get the current channel locking status
      operationId: getChannelLock
      parameters:
        - in: path
          name: user_id
          required: true
          description: The identity of the user to fetch lists for.  Please do not use an email address to identify the user.
          schema:
            type: string
      responses:
        200:
          description: "Successful response"
          headers:
            cache-control: "private, max-age=600"
          content:
            application/json:
              schema:
                type: "object"
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - id
                      properties:
                        type:
                          type: string
                          example: UserChannelLockingConfiguration
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "da00a320-2bae-49af-9687-298ed3f01361"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/UserConfiguration/UserChannelLockingConfiguration.yml#/UserChannelLockingConfiguration"

    patch:
      tags:
      - Channel locking
      summary: Set channel locking on or off
      description: |
        * **Available since:** NOT YET AVAILABLE
        * The "pin_code" field is used for the API server to help the client verify that the PIN entered matches the one stored for the account.
        * The "new_pin_code" field should only be present if the client is trying to change the stored PIN for the account.
        * The API will not track session locking status (this is entirely for the client) but will verify that the supplied PIN code is correct when the client requests this to be changed.
      operationId: setChannelLock
      parameters:
        - in: path
          name: user_id
          required: true
          description: The identity of the user to fetch lists for.  Please do not use an email address to identify the user.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/UserConfiguration/UserChannelLockingConfiguration.yml#/UserChannelLockingConfiguration"
      responses:
        204:
          description: |
            The resource was updated successfully, no response body is needed

        403:
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/ErrorEntity.yml#/Error"
                example:
                  id: 9303f876
                  code: f223db3
                  title: PIN code incorrect
                  details: >-
                    The PIN code that you supplied does not match the one we have stored for the account.



