openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Recordings"
tags:
- name: Individual recordings
- name: Recording Groups
- name: Playhead control
- name: Catchup
servers:
- url: 'https://boox.fi/api'
paths:

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Recordings
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /user/{user_id}/recording/search:
    get:
      summary: This endpoint can be used to return a list of recordings that are filtered by search criteria
      description: >-
        A user performs a search by applying GET method to "search" resource within "recording.
        If the start-time (st) is specified, it will limit the results to programs with start-time equal or greater than "st" value.
        If the end-time (et) is specified, it will limit the results to programs with start time equal or less than "et" value.
        A user can limit the amount of information returned by specifying the number of items to return in a single response (ipp)
        and page-number (pg) of the result. More results can retrieve by the user by incrementing the page-number, till the results
        in the response are lesser than the maximum number of items per page. If the items per page are greater than a server-configurable
        max-value, only max-items are returned. The page-number starts from 1. "search_in" parameters can be title, description and category.
        "keyword" parameter is mandatory if "search_in" is specified. "sort" parameter can be used to define the order in which the results
        are shown. By default, the results are sorted in descending order of start-date ("start_date__desc"), with newest items in the
        start. Other options are "rec_count__desc", which will sort it according to number of times the item is asked to be recorded by different users.
        "recordings" array will always return at least 2 streams even if the recording only has one.
        This is due to legacy WBox compatibility which always gets the second stream from the recording.
      tags:
      - Electronic Program Guide
      operationId: indexGuide
      parameters:
      - in: query
        name: service_token
        description: Service to which the user belongs.
        required: true
        schema:
          type: string
      - in: query
        name: user_id
        description: The email address of the user
        required: true
        schema:
          type: string
      - in: query
        name: st
        description: Date and time where to start the recording information
        required: false
        schema:
          type: integer
      - in: query
        name: et
        description: Date and time where to end the recording information
        required: false
        schema:
          type: integer
      - in: query
        name: pg
        description: Page number if the results have more items than ipp. Default = 0
        required: false
        schema:
          type: integer
      - in: query
        name: ipp
        description: Maximum number of result items per page. Default = 1000
        required: false
        schema:
          type: integer
      - in: query
        name: ch
        description: List of channel IDs, separated by comma. Defaults of all channels
        required: false
        schema:
          type: string
      - in: query
        name: keyword
        description: Keyword to match in program information. Defaults to match with all recordings of the user
        required: false
        schema:
          type: string
      - in: query
        name: search_in
        description: >-
          Searches for keyword in defined fields.  Defaults to "title" of the recording
        required: false
        schema:
          type: string
          enum: ["title", "description", "category", "program_uid"]
      - in: query
        name: cat
        description: Comma separted list of program category ids. They are used to search by title or description within category
        required: false
        schema:
          type: string
      - in: query
        name: sort
        description: Sorting criteria for the results. Defaults to “start_date__desc”
        required: false
        schema:
          type: string
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                type: object
                required:
                - storage
                - recordedContent
                properties:
                  storage:
                    type: object
                    required:
                    - total
                    - left
                    properties:
                      storage:
                        type: string
                        example: "100:00:00"
                      left:
                        type: string
                        example: "50:10:00"
                  recordedContent:
                    type: object
                    required:
                    - description
                    - resultSet
                    - totalItems
                    - totalPages
                    - itemsPerPage
                    - currentPage
                    - offset
                    properties:
                      totalItems:
                        type: integer
                        example: 8
                      totalPages:
                        type: integer
                        example: 1
                      itemsPerPage:
                        type: integer
                        example: 10
                      currentPage:
                        type: integer
                        example: 1
                      offset:
                        type: integer
                        example: 0
                  programList:
                    type: object
                    required:
                    - description
                    - language
                    - pubDate
                    - programs
                    properties:
                      description:
                        type: string
                        example: Program listing
                      language:
                        type: string
                        example: "fi-FI"
                      pubDate:
                        type: string
                        example: Mon, 21 Nov 2011 13:47:12 +0200
                      programs:
                        type: array
                        items:
                          type: object
                          required:
                          - category
                          - subCategory
                          - categories
                          - channelId
                          - programUid
                          - showId
                          - programInstanceMetadataId
                          - programCrId
                          - startTime
                          - continuous
                          - autoDelete
                          - favorite
                          - description
                          - duration
                          - playbackDuration
                          - thumbnailUrl
                          properties:
                            category:
                              type: string
                              example: Show/Game show
                            subCategory:
                              type: string
                              example: ""
                            categories:
                              type: array
                              items: string
                              example: ["Sarjat", "Asiaohjelmat", "Show/Game show", "Viihde"]
                            channelId:
                              type: string
                              example: "17"
                            programUid:
                              type: string
                              example: "20111119184517"
                            showId:
                              type: string
                              example: "1-series"
                              description: this key is null if nPVRShowInfo parameter is not enabled and series_id, program_id are null
                            programInstanceMetadataId:
                              type: string
                              example: "647843303"
                              description: This key is is null if metadata module is not enabled
                            programCrId:
                              type: string
                              example: "192867475"
                              description: This key is is null if metadata module is not enabled
                            startTime:
                              type: string
                              example: "Sat, 19 Nov 2011 16:45:33 +0200"
                            continuous:
                              type: boolean
                              example: true
                            autoDelete:
                              type: boolean
                              example: true
                            favorite:
                              type: boolean
                              example: false
                            description:
                              type: string
                              example: >-
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut risus et mi rutrum aliquet.
                                Praesent feugiat condimentum arcu sit amet gravida. Proin vitae sapien lorem. Sed tortor mauris,
                                pellentesque non dui in, lobortis cursus lorem. Ut porta, ante aliquet lacinia ultricies, massa
                                dolor mattis diam, ultricies fermentum ex orci vel tellus. Ut et volutpat sapien.
                            duration:
                              type: integer
                              example: 3055,
                            playbackDuration:
                              type: integer
                              example: 1258,
                            thumbnailUrl:
                              type: string
                              example: ""
                            recordings:
                              type: array
                              items:
                                type: object
                                required:
                                - stream
                                - recorded_duration
                                - status
                                - recording_id
                                properties:
                                  stream:
                                    type: object
                                    required:
                                    - bitrate
                                    - type
                                    - protocol
                                    - streamUrl
                                    properties:
                                      bitrate:
                                        type: integer
                                        example: 256
                                      type:
                                        type: string
                                        example: video/mp4
                                      protocol:
                                        type: string
                                        example: http
                                      streamUrl:
                                        type: string
                                        example: http://media-host/yle1-20111119_1845-2985-622a89739e1dd6e9158e61dab5c14d35?email=waqqas%40test.com&usid=4eca4ff14ed867.60829558
                                  recorded_duration:
                                    type: integer
                                    example: 525
                                  status:
                                    type: string
                                    example: "SCHEDULED"
                                  recording_id:
                                    type: integer
                                    example: 1234
                            fastForwardPvr:
                              type: boolean
                              example: false
                            retentionTime:
                              type: integer
                              example: 7

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Groups
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Playhead
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
