openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Catchup"
tags:
- name: Catchup items
servers:
- url: 'https://demo.aminocom.com/api/metadata/v1/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
- bearerAuth: []         # use the same name as above
paths:

# --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /catchup:

    get:
      summary: Get an index of Catchup items
      description:  Note that we do not support including related resources in the index view.
      tags:
      - Catchup items
      operationId: GetCatchupItems
      parameters:
        - in: query
          name: language
          required: false
          description: >-
            The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).
            If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.
            If the requested language is not available then the system will return translations in order of the system defined preferences
          schema:
            type: string
        - in: query
          name: filter
          required: true
          schema:
            type: string
          description: >-
            See https://jsonapi.org/recommendations/#filtering
            This endpoint only supports filtering on [channel.id|series.id|program.title] and supports multiple values through csv.
            It is compulsory to include at least the channel.id filter.  A wildcard of "*" indicates that all channels must be included.
          enum: [channel.id, series.id, program.title]
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - id
                      properties:
                        type:
                          type: string
                          example: CatchupItem
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "f50a8a6b-e96a-4eb7-8d87-a14c1a991b96"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/Schedule/CatchupItem.yml#/CatchupItem"

        400:
          description: Standard error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/ErrorEntity.yml#/Error"