openapi: 3.0.0
info:
  description: >-
    Authentication is the process or action of proving or showing something to be true, genuine, or valid.
  version: 1.0.0
  title: Authentication
tags:
- name: Account Authentication
servers:
- url: 'https://demo.aminocom.com/api/auth/v1/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
- bearerAuth: []         # use the same name as above
paths:

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


  /access_tokens:
    post:
      summary: |
        Create an access token that can be used to authenticate to the API.  Note that there is no session involved,
        the API is stateless and the access token needs to be presented with every call.
      tags:
      - Account Authentication
      operationId: createAccessToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - grant_type
              - credentials
              properties:
                grant_type:
                  type: string
                  example: refresh_token
                  enum: [refresh_token]
                credentials:
                  type: object
                  properties:
                    refresh_token:
                      type: string
                      description: >-
                          The refresh token that was issued at the same time as an access token.
                      example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJFbmFibGVTVEIiLCJpYXQiOjE1MzE4MzQyNDEsImV4cCI6MTU2MzM3MDI0MSwiYXVkIjoid3d3LmFtaW5vY29tLmNvbSIsInN1YiI6ImFuZHkuYmVha0BhbWlub2NvbS5jb20ifQ.jtTwO3YEyXmEf5XjjxUK8V_MPRvxdi7DN1eEBUyjfkE

      responses:
        '201':
          description: |
            Successful response.
          headers:
            cache-control: "no-cache, no-store, must-revalidate"
          content:
            text/plain:
              schema:
                type: "object"
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - id
                      properties:
                        type:
                          type: string
                          example: AccessToken
                        id:
                          type: string
                          description: "The id of the entity being referenced"
                          example: "9bc6871e-ce26-4b8a-96f6-e6688599d938"
                        attributes:
                          $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/Auth/AccessToken.yml#/AccessToken"


        '400':
          description: Standard error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/ErrorEntity.yml#/Error"

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /access_token/{access_token_id}:
    delete:
      summary: |
        Invalidate an access token (and its associated refresh token).  You must supply the access token as authentication to this endpoint.
        The API will verify that the jti of the supplied access token matches the access_token_id you want to delete.
      tags:
      - Account Authentication
      operationId: deleteAccessToken
      parameters:
        - in: path
          name: user_id
          required: true
          description: The user identity (please do not use an email address to identify the user)
          schema:
            type: string
        - in: path
          name: access_token_id
          required: true
          description: The id of the access token to revoke
          schema:
            type: string

      responses:
        '204':
          description: |
            The user session was deleted successfully

        '400':
          description: Standard error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/ErrorEntity.yml#/Error"

