swagger: "2.0"
info:
  description: |
    An Episode is an individual Program in a Series. It belongs to a Season.
  version: "1.0.0"
  title: "Episode endpoints"
externalDocs:
  description: "Original ticket"
  url: "https://jira.aminocom.com/browse/BPLAT-4173"
host: "demo.aminocom.com"
basePath: "/api/epg/v1/"
tags:
- name: "Episodes"
  description: ""
schemes:
- "https"
paths:

  /episodes:
    get:
      summary: "Get an index of episodes"
      tags:
      - "Episodes"
      operationId: "GetEpisodeIndex"
      produces:
      - "application/json"
      parameters:
      - in: query
        name: language
        type: string
        required: false
        description: "The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).  If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.  If the requested language is not available then the system will return translations in order of the system defined preferences"

      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            required:
            - data
            properties:
              data:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - id
                  properties:
                    type:
                      type: string
                      example: Episode
                    id:
                      type: string
                      description: "The id of the entity being referenced"
                      example: "3173335a-810b-4b53-b009-122a169f9920"
                    attributes:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/snippets/EnrichedMetadata/EpisodeEntity.yml#EpisodeEntity"





  /episodes/{episode_id}:
    get:
      summary: "Get a specific episode.  The PK of the episode is the program_id which is an FK to the id of the program."
      tags:
      - "Episodes"
      operationId: "GetEpisode"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "episode_id"
        type: "string"
        required: true
        description: "The identifier of the episode"
      - in: query
        name: language
        type: string
        required: false
        description: "The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).  If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.  If the requested language is not available then the system will return translations in order of the system defined preferences"

      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            required:
            - data
            properties:
              data:
                type: object
                required:
                - type
                - id
                properties:
                  type:
                    type: string
                    example: Episode
                  id:
                    type: string
                    description: "The id of the entity being referenced"
                    example: "3173335a-810b-4b53-b009-122a169f9920"
                  attributes:
                    $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/snippets/EnrichedMetadata/EpisodeEntity.yml#EpisodeEntity"

        404:
          description: "Not found (either the program does not exist or it is not an episode of a series)"
          schema:
            type: "object"
            properties:
              errors:
                $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/snippets/General/ErrorEntity.yml#Error"





  /episodes/{episode_id}/programs:
    get:
      summary: "Get the program for an episode.  This is a one-to-one relationship."
      tags:
      - "Episodes"
      operationId: "GetEpisodePrograms"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "episode_id"
        type: "string"
        required: true
        description: "The identifier of the episode"
      - in: query
        name: language
        type: string
        required: false
        description: "The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).  If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.  If the requested language is not available then the system will return translations in order of the system defined preferences"

      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            required:
            - data
            properties:
              data:
                type: object
                required:
                - type
                - id
                properties:
                  type:
                    type: string
                    example: Program
                  id:
                    type: string
                    description: "The id of the entity being referenced"
                    example: "cc96d60f-8dc3-4a00-9d1f-761fe4933d8a"
                  attributes:
                    $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/snippets/EnrichedMetadata/ProgramEntity.yml#ProgramEntity"
