swagger: "2.0"
info:
  description: |
    A program is something that can be shown.
    It could be a television show (like "Friends") or a movie (like "Die Hard") that appears on a Channel at a given time in a BroadcastSlot.
    It could equally be a VOD item that can be played on demand.
    The entity "Program" is a hook into the metadata system and does not include any information about when (or how) the thing can be played.  It's just information about what can be played.
  version: "1.0.0"
  title: "Program endpoints"
externalDocs:
  description: "Original ticket"
  url: "https://jira.aminocom.com/browse/BPLAT-4173"
host: "demo.aminocom.com"
basePath: "/api/epg/v1/"
tags:
- name: "Programs"
  description: ""
schemes:
- "https"
paths:

  /programs:
    get:
      summary: "Get an index of programs.  By default you should return this list sorted by release_year descending and force pagination (100 results per page).  NOTE:  there is a Swagger limitation that includes the `series` relationship into the entities, ignore this for this endpoint"
      tags:
      - "Programs"
      operationId: "GetProgramIndex"
      produces:
      - "application/json"
      parameters:
      - in: query
        name: language
        type: string
        required: false
        description: "The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).  If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.  If the requested language is not available then the system will return translations in order of the system defined preferences"
      - in: query
        name: page_number
        type: integer
        required: false
        description: "The page number (100 results per page) of results to retrieve.  If this parameter is ommitted then it is assumed to be 1 (not zero based, 1 means the first page)"

      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            required:
            - data
            properties:
              data:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - id
                  properties:
                    type:
                      type: string
                      example: Program
                    id:
                      type: string
                      description: "The id of the entity being referenced"
                      example: "3173335a-810b-4b53-b009-122a169f9920"
                    attributes:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/snippets/EnrichedMetadata/ProgramEntity.yml#ProgramEntity"


  /programs/{program_id}:
    get:
      summary: "Get a specific program.  NOTE:  This endpoint will *always* include [Series|Episode|Season] relationships and DOES NOT support the `included` parameter."
      tags:
      - "Programs"
      operationId: "GetProgram"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "program_id"
        type: "string"
        required: true
        description: "The identifier of the program"
      - in: query
        name: language
        type: string
        required: false
        description: "The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).  If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.  If the requested language is not available then the system will return translations in order of the system defined preferences"

      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            required:
            - data
            properties:
              data:
                type: object
                required:
                - type
                - id
                properties:
                  type:
                    type: string
                    example: Program
                  id:
                    type: string
                    description: "The id of the entity being referenced"
                    example: "3173335a-810b-4b53-b009-122a169f9920"
                  attributes:
                    $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/snippets/EnrichedMetadata/ProgramEntity.yml#ProgramEntity"
              included:
                type: array
                description: "This key MUST NOT be included if the `included` parameter is not used in the request URL"
                items:
                  type: object
                  description: "Note that different sorts of entity may be included (this array is not guaranteed to be homogenous), but the Swagger definition does not allow including more than one example of an item of an array so only one type is shown."
                  properties:
                    type:
                      type: string
                      example: "Series"
                      description: The type of the entity that is being included.  It will be one of [Series|Episode|Season]
                    id:
                      type: string
                      example: "f9df1401-9d25-48e0-b5d6-0745a86bd975"
                    attributes:
                        $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/snippets/EnrichedMetadata/SeriesEntity.yml#SeriesEntity"
