swagger: "2.0"
info:
  description: |
    Multiple Programs are grouped into a Series which consists of several Episodes that belong to Seasons
    A Program can be either part of a Series (in which case it is an Episode) or stand alone.
    Note: The plural of a single Series is Series
  version: "1.0.0"
  title: "Series endpoints"
externalDocs:
  description: "Original ticket"
  url: "https://jira.aminocom.com/browse/BPLAT-4173"
host: "demo.aminocom.com"
basePath: "/api/epg/v1/"
tags:
- name: "Series"
  description: ""
schemes:
- "https"
paths:

  /series:
    get:
      summary: "Get an index of series"
      tags:
      - "Series"
      operationId: "GetSeriesIndex"
      produces:
      - "application/json"
      parameters:
      - in: query
        name: language
        type: string
        required: false
        description: "The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).  If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.  If the requested language is not available then the system will return translations in order of the system defined preferences"

      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            required:
            - data
            properties:
              data:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - id
                  properties:
                    type:
                      type: string
                      example: Series
                    id:
                      type: string
                      description: "The id of the entity being referenced"
                      example: "f9df1401-9d25-48e0-b5d6-0745a86bd975"
                    attributes:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/snippets/EnrichedMetadata/SeriesEntity.yml#SeriesEntity"



  /series/{series_id}:
    get:
      summary: "Get an individual series"
      tags:
      - "Series"
      operationId: "GetSeriesEntity"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "series_id"
        type: "string"
        required: true
        description: "The identifier of the series"
      - in: query
        name: language
        type: string
        required: false
        description: "The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).  If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.  If the requested language is not available then the system will return translations in order of the system defined preferences"

      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            required:
            - data
            properties:
              data:
                type: object
                required:
                - type
                - id
                properties:
                  type:
                    type: string
                    example: Series
                  id:
                    type: string
                    description: "The id of the entity being referenced"
                    example: "f9df1401-9d25-48e0-b5d6-0745a86bd975"
                  attributes:
                    $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/snippets/EnrichedMetadata/SeriesEntity.yml#SeriesEntity"



  /series/{series_id}/programs:
    get:
      summary: "Get list of programs for a series - this should only be Programs that are *directly* related to a Series and NOT Programs that are transitively related through an Episode."
      tags:
      - "Series"
      operationId: "SeeSeriesPrograms"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "series_id"
        type: "string"
        required: true
        description: "The identifier of the series"
      - in: query
        name: language
        type: string
        required: false
        description: "The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).  If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.  If the requested language is not available then the system will return translations in order of the system defined preferences"

      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            required:
            - data
            properties:
              data:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - id
                  properties:
                    type:
                      type: string
                      example: Program
                    id:
                      type: string
                      description: "The id of the entity being referenced"
                      example: "cc96d60f-8dc3-4a00-9d1f-761fe4933d8a"
                    attributes:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/snippets/EnrichedMetadata/ProgramEntity.yml#ProgramEntity"



  /series/{series_id}/seasons:
    get:
      summary: "Get list of seasons for a series.  (Note:  There is a transitive relationship to Episodes through Seasons)"
      tags:
      - "Series"
      operationId: "SeeSeriesSeasons"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "series_id"
        type: "string"
        required: true
        description: "The identifier of the series"
      - in: query
        name: language
        type: string
        required: false
        description: "The PK of the language to use, which will be a 3 character ISO 639-2 string (e.g.: fin).  If this is omitted the browser 'Accept-Language' will be used if it is available, and otherwise the system defined default.  If the requested language is not available then the system will return translations in order of the system defined preferences"

      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            required:
            - data
            properties:
              data:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - id
                  properties:
                    type:
                      type: string
                      example: Season
                    id:
                      type: string
                      description: "The id of the entity being referenced"
                      example: "feaf803a-3ca9-4d2e-b86b-9d217183efc5"
                    attributes:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/snippets/EnrichedMetadata/SeasonEntity.yml#SeasonEntity"
